apiVersion: apps/v1
kind: Deployment
metadata:
  name: chinhpv6-capstone-app-1-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chinhpv6-capstone-app
      version: 1-0
  template:
    metadata:
      labels:
        app: chinhpv6-capstone-app
        version: 1-0
    spec:
      containers:
      - name: chinhpv6-capstone-app
        image: tireallife1023/chinhpv6-capstone-app:1.0
        ports:
        - containerPort: 80
